name: CI
on:
  push:
    branches: [ refs/heads/master ]
  pull_request:
    branches: [ refs/heads/master ]
jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/Wellcentive/PInC
            azure-pipeline-name: UC_SDK_TESTAPP
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
